# Generated by Django 5.1.4 on 2025-01-01 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_manufacterer_name_manufacturer_manufacturer_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
